# Order of inclusion matters!
include("AbstractShape.jl")
include("AbstractObject.jl")
include("AbstractObjectGroup.jl")
include("AbstractMedium.jl")
include("AbstractSurfaceModel.jl")
include("AbstractVolumeModel.jl")
include("AbstractCoating.jl")
include("AbstractShapeTrait.jl")
include("AbstractIntersection.jl")
include("AbstractSegment.jl")
include("AbstractRay.jl")
include("AbstractBeam.jl")
include("AbstractGaussian.jl")
include("AbstractSystem.jl")
