.script:
  variables: 
    CI: "true"
  script:
    - |
      D:/CI_Ressources/Julia-1.8.0-rc3/bin/julia.exe --project=@. -e '
        using Pkg        
        Pkg.test(coverage=true)'
.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
       D:/CI_Ressources/Julia-1.8.0-rc3/bin/julia.exe -e '
        using Pkg
        Pkg.add(\"Coverage\")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf \"Test coverage %.2f%%\n\" 100c / t'
Julia 1.8:
  image: julia:1.8
  extends:
    - .script
    - .coverage