.script:
  variables: 
    CI: "true"
  script:
    - |
      D:/CI_Ressources/Julia-1.10.2/bin/julia.exe --project=@. -e '
        using Pkg        
        Pkg.test(coverage=true)'
.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
       D:/CI_Ressources/Julia-1.10.2/bin/julia.exe -e '
        using Pkg
        Pkg.add(\"Coverage\")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf \"Test coverage %.2f%%\n\" 100c / t'
Julia 1.10:
  image: julia:1.10
  extends:
    - .script
    - .coverage
pages:
  image: julia:1.10
  stage: deploy
  script:
    - |
       D:/CI_Ressources/Julia-1.10.2/bin/julia.exe --project=docs -e '
        using Pkg
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()
        using Documenter: doctest
        using SCDI
        doctest(SCDI)
        include(\"docs/make.jl\")'
    - mkdir -p public
    - mv docs/build/* public/
  artifacts:
    paths:
      - public  
  only:
    - main